sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "7"
before_script:
  - npm i
script:
  - npm t
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
